import type { MetaUpgradeDef } from '../types'

export const META_UPGRADES: MetaUpgradeDef[] = [
  {
    id: 'meta_damage',
    name: 'Combat Training',
    description: 'Permanently increase base damage.',
    category: 'combat',
    maxLevel: 10,
    baseCost: 100,
    costMultiplier: 1.4,
    currency: 'credits',
    effect: { type: 'stat', stat: 'damageMult', value: 0.03, mode: 'mult' },
  },
  {
    id: 'meta_health',
    name: 'Toughened Sinews',
    description: 'Permanently increase base health.',
    category: 'combat',
    maxLevel: 10,
    baseCost: 100,
    costMultiplier: 1.4,
    currency: 'credits',
    effect: { type: 'stat', stat: 'maxHealthBonus', value: 0.05, mode: 'mult' },
  },
  {
    id: 'meta_speed',
    name: 'Neural Accelerator',
    description: 'Permanently increase movement speed.',
    category: 'combat',
    maxLevel: 8,
    baseCost: 150,
    costMultiplier: 1.5,
    currency: 'credits',
    effect: { type: 'stat', stat: 'speedMult', value: 0.03, mode: 'mult' },
  },
  {
    id: 'meta_credits',
    name: 'Resource Optimizer',
    description: 'Earn more credits per run.',
    category: 'economy',
    maxLevel: 10,
    baseCost: 50,
    costMultiplier: 1.5,
    currency: 'credits',
    effect: { type: 'stat', stat: 'xpGainMult', value: 0.05, mode: 'mult' },
  },
  {
    id: 'meta_minerals',
    name: 'Mineral Scanner',
    description: 'Start each run with extra minerals.',
    category: 'economy',
    maxLevel: 8,
    baseCost: 200,
    costMultiplier: 1.6,
    currency: 'credits',
    effect: { type: 'stat', stat: 'pickupRadius', value: 10, mode: 'add' },
  },
  {
    id: 'meta_start_minigun',
    name: 'Arsenal Access',
    description: 'Start each run with the Minigun unlocked.',
    category: 'unlock',
    maxLevel: 1,
    baseCost: 500,
    costMultiplier: 1,
    currency: 'credits',
    effect: { type: 'stat', stat: 'damageMult', value: 0, mode: 'add' },
  },
  {
    id: 'meta_luck',
    name: 'Tactical Intuition',
    description: 'Better upgrade choices appear more often.',
    category: 'utility',
    maxLevel: 5,
    baseCost: 300,
    costMultiplier: 1.8,
    currency: 'credits',
    effect: { type: 'stat', stat: 'criticalChance', value: 0.01, mode: 'add' },
  },
]
