import type { SkillTreeBranchConfig } from '../types/game';

export const SKILL_TREE_CONFIG: SkillTreeBranchConfig[] = [
  {
    id: 'command',
    name: 'Command',
    title: 'Battlefield Command',
    accent: 'rgba(0, 242, 255, 0.9)',
    nodes: [
      {
        id: 'command-scan',
        branch: 'command',
        name: 'Тактичне сканування',
        description: 'Збільште приріст досвіду та радіус захоплення для чистішого удару на полі бою.',
        cost: 1,
        mineralCost: 150,
        gasCost: 0,
        maxRank: 3,
        effects: [
          { type: 'stat', stat: 'xpGainMult', value: 0.1, mode: 'mult' },
          { type: 'stat', stat: 'pickupRadius', value: 20, mode: 'add' },
        ],
        tag: 'Support',
      },
      {
        id: 'command-focus-fire',
        branch: 'command',
        name: 'Focus Fire Doctrine',
        description: 'Sharpen target acquisition, increasing critical strike chance.',
        cost: 1,
        mineralCost: 250,
        gasCost: 50,
        maxRank: 4,
        prerequisites: ['command-scan'],
        effects: [{ type: 'stat', stat: 'criticalChance', value: 0.04, mode: 'add' }],
        tag: 'Targeting',
      },
      {
        id: 'command-field-med',
        branch: 'command',
        name: 'Field Med Bay',
        description: 'Trigger a small health burst whenever you invest in this doctrine.',
        cost: 1,
        mineralCost: 400,
        gasCost: 150,
        maxRank: 2,
        prerequisites: ['command-focus-fire'],
        effects: [{ type: 'health_burst', value: 18 }],
        tag: 'Sustain',
      },
    ],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    title: 'Terran Arsenal',
    accent: 'rgba(255, 191, 60, 0.9)',
    nodes: [
      {
        id: 'arsenal-ballistics',
        branch: 'arsenal',
        name: 'Ballistics Training',
        description: 'Boost rifle damage and projectile speed.',
        cost: 1,
        mineralCost: 100,
        gasCost: 0,
        maxRank: 5,
        effects: [
          { type: 'stat', stat: 'damageMult', value: 0.12, mode: 'mult' },
          { type: 'stat', stat: 'projectileSpeedMult', value: 0.08, mode: 'mult' },
        ],
        tag: 'Ranged',
      },
      {
        id: 'arsenal-fire-control',
        branch: 'arsenal',
        name: 'Fire Control',
        description: 'Increase fire rate and projectile count for sustained suppression.',
        cost: 1,
        mineralCost: 200,
        gasCost: 50,
        maxRank: 4,
        prerequisites: ['arsenal-ballistics'],
        effects: [
          { type: 'stat', stat: 'fireRateMult', value: 0.14, mode: 'mult' },
          { type: 'stat', stat: 'projectileCountBonus', value: 1, mode: 'add' },
        ],
        tag: 'Suppression',
      },
      {
        id: 'arsenal-minigun',
        branch: 'arsenal',
        name: 'Minigun Assembly',
        description: 'Unlock the Minigun for dense bullet streams and close-range shredding.',
        cost: 1,
        mineralCost: 400,
        gasCost: 150,
        maxRank: 1,
        prerequisites: ['arsenal-fire-control'],
        effects: [{ type: 'weapon_unlock', weaponId: 'minigun' }],
        tag: 'Unlock',
      },
      {
        id: 'arsenal-rocket',
        branch: 'arsenal',
        name: 'Rocket Barrage',
        description: 'Unlock the Rocket Launcher for explosive crowd control.',
        cost: 1,
        mineralCost: 600,
        gasCost: 250,
        maxRank: 1,
        prerequisites: ['arsenal-minigun'],
        effects: [{ type: 'weapon_unlock', weaponId: 'rocket_launcher' }],
        tag: 'Unlock',
      },
      {
        id: 'arsenal-plasma',
        branch: 'arsenal',
        name: 'Plasma Cannon',
        description: 'Unlock the Plasma Cannon to pierce elite packs and bosses.',
        cost: 1,
        mineralCost: 800,
        gasCost: 400,
        maxRank: 1,
        prerequisites: ['arsenal-rocket'],
        effects: [{ type: 'weapon_unlock', weaponId: 'plasma_cannon' }],
        tag: 'Unlock',
      },
    ],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    title: 'Field Engineering',
    accent: 'rgba(0, 255, 65, 0.9)',
    nodes: [
      {
        id: 'engineering-plating',
        branch: 'engineering',
        name: 'Reactive Plating',
        description: 'Increase maximum health and armor plating.',
        cost: 1,
        mineralCost: 150,
        gasCost: 0,
        maxRank: 5,
        effects: [
          { type: 'stat', stat: 'maxHealthBonus', value: 0.12, mode: 'mult' },
          { type: 'stat', stat: 'armor', value: 1, mode: 'add' },
        ],
        tag: 'Defense',
      },
      {
        id: 'engineering-recovery',
        branch: 'engineering',
        name: 'Rapid Recovery',
        description: 'Recover a small amount of health on elite kill events.',
        cost: 1,
        mineralCost: 250,
        gasCost: 75,
        maxRank: 3,
        prerequisites: ['engineering-plating'],
        effects: [{ type: 'health_burst', value: 12 }],
        tag: 'Heal',
      },
      {
        id: 'engineering-bolters',
        branch: 'engineering',
        name: 'Heavy Bolters',
        description: 'Increase weapon projectile size for better hit coverage.',
        cost: 1,
        mineralCost: 350,
        gasCost: 150,
        maxRank: 4,
        prerequisites: ['engineering-recovery'],
        effects: [{ type: 'stat', stat: 'projectileSizeMult', value: 0.15, mode: 'mult' }],
        tag: 'Firepower',
      },
    ],
  },
  {
    id: 'mobility',
    name: 'Mobility',
    title: 'Mobility Matrix',
    accent: 'rgba(109, 178, 255, 0.9)',
    nodes: [
      {
        id: 'mobility-servo',
        branch: 'mobility',
        name: 'Servo Boosters',
        description: 'Improve move speed and tactical responsiveness.',
        cost: 1,
        mineralCost: 100,
        gasCost: 0,
        maxRank: 5,
        effects: [{ type: 'stat', stat: 'speedMult', value: 0.1, mode: 'mult' }],
        tag: 'Move',
      },
      {
        id: 'mobility-shields',
        branch: 'mobility',
        name: 'Shield Arrays',
        description: 'Increase max health and pickup radius for safer routing.',
        cost: 1,
        mineralCost: 200,
        gasCost: 75,
        maxRank: 3,
        prerequisites: ['mobility-servo'],
        effects: [
          { type: 'stat', stat: 'maxHealthBonus', value: 0.08, mode: 'mult' },
          { type: 'stat', stat: 'pickupRadius', value: 18, mode: 'add' },
        ],
        tag: 'Utility',
      },
      {
        id: 'mobility-ordinance',
        branch: 'mobility',
        name: 'Ordnance Relay',
        description: 'Unlock or upgrade Orbital Laser support fire.',
        cost: 1,
        mineralCost: 500,
        gasCost: 300,
        maxRank: 3,
        prerequisites: ['mobility-shields'],
        effects: [{ type: 'weapon_rank', weaponId: 'orbital_laser', value: 1 }],
        tag: 'Support',
      },
    ],
  },
];
